# encoding: utf-8
"""
BIM Health Scorecard - Excel writer (host-side, run with system Python + openpyxl).
Reads outputs/scorecard_data.json (written by the Revit-side engine) and produces
a formatted .xlsx scorecard: Summary, Rule Detail, Failing Elements.

Usage:  py build_scorecard.py
"""
import json, os, sys

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "outputs", "scorecard_data.json")

GRADE_FILL = {  # letter -> hex fill
    "A": "2E7D32", "B": "7CB342", "C": "F9A825", "D": "EF6C00", "F": "C62828",
}
HDR_FILL = "1F3A5F"
WHITE = "FFFFFF"
GREY = "F2F2F2"
thin = Side(style="thin", color="D0D0D0")
BORDER = Border(left=thin, right=thin, top=thin, bottom=thin)

def grade_fill(letter):
    return PatternFill("solid", fgColor=GRADE_FILL.get(letter, "9E9E9E"))

def passfill(pct):
    if pct >= 90: c = "C8E6C9"
    elif pct >= 70: c = "FFF9C4"
    elif pct >= 40: c = "FFE0B2"
    else: c = "FFCDD2"
    return PatternFill("solid", fgColor=c)

def hdr(cell):
    cell.font = Font(bold=True, color=WHITE, size=11)
    cell.fill = PatternFill("solid", fgColor=HDR_FILL)
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell.border = BORDER

def main():
    with open(DATA) as f:
        d = json.load(f)

    wb = Workbook()

    # ---------- Sheet 1: Summary ----------
    ws = wb.active
    ws.title = "Scorecard"
    ws.sheet_view.showGridLines = False
    ws.column_dimensions["A"].width = 3
    for col, w in zip("BCDEF", (26, 14, 12, 12, 30)):
        ws.column_dimensions[col].width = w

    ws["B2"] = "BIM HEALTH SCORECARD"
    ws["B2"].font = Font(bold=True, size=20, color=HDR_FILL)
    ws["B3"] = d["model"]
    ws["B3"].font = Font(bold=True, size=12, color="555555")
    ws["B4"] = "Stage: %s   |   generated by AutoConst" % d["stage"]
    ws["B4"].font = Font(size=10, italic=True, color="888888")

    # big overall grade block
    ws.merge_cells("B6:C8")
    g = ws["B6"]
    g.value = "%s\n%.1f / 100" % (d["grade"], d["overall"])
    g.font = Font(bold=True, size=28, color=WHITE)
    g.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    for r in range(6, 9):
        for c in ("B", "C"):
            ws["%s%d" % (c, r)].fill = grade_fill(d["grade"])
    ws["D6"] = "OVERALL"
    ws["D6"].font = Font(bold=True, size=12, color=HDR_FILL)

    # category table
    ws["B10"] = "Category"; ws["C10"] = "Score"; ws["D10"] = "Grade"; ws["E10"] = "Weight"
    for c in "BCDE":
        hdr(ws["%s10" % c])
    order = ["naming", "parameters", "classification", "geometry", "worksharing"]
    row = 11
    cats = d["category_scores"]
    for cat in order:
        if cat not in cats:
            continue
        cs = cats[cat]
        ws["B%d" % row] = cat.capitalize()
        ws["C%d" % row] = cs["score"]
        ws["D%d" % row] = cs["grade"]
        ws["E%d" % row] = "%d%%" % round(cs["weight"] * 100)
        ws["C%d" % row].fill = passfill(cs["score"])
        ws["D%d" % row].fill = grade_fill(cs["grade"])
        ws["D%d" % row].font = Font(bold=True, color=WHITE)
        for c in "BCDE":
            cell = ws["%s%d" % (c, row)]
            cell.border = BORDER
            if c != "B":
                cell.alignment = Alignment(horizontal="center")
        row += 1

    note = ("Grades: A>=90 B>=80 C>=70 D>=60 F<60. Weights are AutoConst methodology "
            "(tunable per BIM Execution Plan). Every rule cites its source on the "
            "Rule Detail tab. Advisory (info) rules are reported but not scored.")
    ws.merge_cells("B%d:F%d" % (row + 1, row + 3))
    nc = ws["B%d" % (row + 1)]
    nc.value = note
    nc.font = Font(size=9, italic=True, color="777777")
    nc.alignment = Alignment(wrap_text=True, vertical="top")

    # ---------- Sheet 2: Rule Detail ----------
    rd = wb.create_sheet("Rule Detail")
    rd.sheet_view.showGridLines = False
    cols = ["Category", "Rule", "Check", "Source", "Severity", "Pass %", "# Fails"]
    widths = [14, 12, 34, 14, 10, 9, 9]
    for i, (c, w) in enumerate(zip(cols, widths), start=1):
        cell = rd.cell(row=1, column=i, value=c); hdr(cell)
        rd.column_dimensions[get_column_letter(i)].width = w
    r = 2
    for rule in d["rules"]:
        pct = round(rule["passrate"] * 100)
        sev = rule["sev"] + (" (adv)" if rule.get("na") else "")
        vals = [rule["cat"], rule["id"], rule["name"], rule["src"], sev, pct, len(rule["fails"])]
        for i, v in enumerate(vals, start=1):
            cell = rd.cell(row=r, column=i, value=v)
            cell.border = BORDER
            if i in (5, 6, 7):
                cell.alignment = Alignment(horizontal="center")
        rd.cell(row=r, column=6).fill = passfill(pct)
        if r % 2 == 0:
            for i in range(1, 8):
                if i != 6:
                    rd.cell(row=r, column=i).fill = PatternFill("solid", fgColor=GREY)
        r += 1
    rd.freeze_panes = "A2"

    # ---------- Sheet 3: Failing Elements ----------
    fe = wb.create_sheet("Failing Elements")
    fe.sheet_view.showGridLines = False
    fcols = ["Rule", "Check", "Element Id", "Issue"]
    fwidths = [12, 34, 14, 40]
    for i, (c, w) in enumerate(zip(fcols, fwidths), start=1):
        cell = fe.cell(row=1, column=i, value=c); hdr(cell)
        fe.column_dimensions[get_column_letter(i)].width = w
    r = 2
    for rule in d["rules"]:
        for eid, issue in rule["fails"]:
            fe.cell(row=r, column=1, value=rule["id"]).border = BORDER
            fe.cell(row=r, column=2, value=rule["name"]).border = BORDER
            fe.cell(row=r, column=3, value=eid).border = BORDER
            fe.cell(row=r, column=4, value=issue).border = BORDER
            r += 1
    if r == 2:
        fe.cell(row=2, column=1, value="No failing elements recorded.")
    fe.freeze_panes = "A2"

    model_safe = "".join(ch for ch in d["model"] if ch.isalnum() or ch in " -_").strip().replace(" ", "-")
    out = os.path.join(ROOT, "outputs", "BIM-Health-Scorecard-%s.xlsx" % model_safe)
    wb.save(out)
    print("WROTE", out)

if __name__ == "__main__":
    main()
